### ISSUE TITLE
'is not' is not != or is it 'is not' != != ?  :-) Minor issue with bootstrap.py in engine when using Python 3.10

### ISSUE THREAD

**Issue by dovanbel** [shotgunsoftware/tk-houdini#72]
Hi,

When launching Houdini 20.0.590 (which is using Python 3.10) with tk-houdini 1.8.7  I get an error message : 

\\VSERVER01\shotgun\Xavier_RD_2024\install\app_store\tk-houdini\v1.8.7\python\tk_houdini\bootstrap.py:246: SyntaxWarning: "is not" with a literal. Did you mean "!="?

Regards

**Comment by julien-lang** [comment]
Hi @dovanbel, thanks for this report.

This warning has been fixed in #71. It's already fixed in master and will be part of the next release of tk-houdini. 
Since this was only a warning, we did not prioritize a component release yet.

**Comment by dovanbel** [comment]
Thanks Julien, indeed a very minor thing.
    On Thursday, February 15, 2024 at 07:29:07 PM GMT+1, Julien Langlois ***@***.***> wrote:  
 
 


Hi @dovanbel, thanks for this report.

This warning has been fixed in #71. It's already fixed in master and will be part of the next release of tk-houdini.
Since this was only a warning, we did not prioritize a component release yet.
